### ISSUE TITLE
yar 502

### ISSUE THREAD

**Issue by zuozhehao** [laruence/yar#161]
php7.3.18，yar 2.1.2
```
#0  0x00007fa0cb3052c7 in raise () from /usr/lib64/libc.so.6
#1  0x00007fa0cb3069b8 in abort () from /usr/lib64/libc.so.6
#2  0x00007fa0cb2fe0e6 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007fa0cb2fe192 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x0000000000b349ca in zval_get_string_func (op=0x7fa0c7817e08) at /tmp/php-7.3.18/Zend/zend_operators.c:898
#5  0x0000000000b40067 in zend_make_printable_zval (expr=0x7fa0c7817e08, expr_copy=0x7ffd06c00710) at /tmp/php-7.3.18/Zend/zend.c:350
#6  0x00007fa0bfa9f5ac in php_yar_get_function_declaration (fptr=0x7fa0c78171e8) at /tmp/yaconf-1.1.0/yar-2.1.2/yar_server.c:278
#7  0x00007fa0bfa9f79f in php_yar_print_info (ptr=0x7fa0c7974100, argument=0x7fa0c7816fc8) at /tmp/yaconf-1.1.0/yar-2.1.2/yar_server.c:321
#8  0x0000000000b58b0a in zend_hash_apply_with_argument (ht=0x7fa0c7817008, apply_func=0x7fa0bfa9f737 <php_yar_print_info>, argument=0x7fa0c7816fc8)
    at /tmp/php-7.3.18/Zend/zend_hash.c:1713
#9  0x00007fa0bfaa080d in php_yar_server_info (obj=0x7fa0c78f1a48) at /tmp/yaconf-1.1.0/yar-2.1.2/yar_server.c:598
#10 0x00007fa0bfaa09ca in zim_yar_server_handle (execute_data=0x7fa0c7820420, return_value=0x7fa0c7820410)
    at /tmp/yaconf-1.1.0/yar-2.1.2/yar_server.c:637
#11 0x0000000000ba7431 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /tmp/php-7.3.18/Zend/zend_vm_execute.h:1106
#12 0x0000000000c0e37e in execute_ex (ex=0x7fa0c78202e0) at /tmp/php-7.3.18/Zend/zend_vm_execute.h:55531
#13 0x0000000000b2b70e in zend_call_function (fci=0x7ffd06c01020, fci_cache=0x7ffd06c01000) at /tmp/php-7.3.18/Zend/zend_execute_API.c:756
#14 0x00007fa0c094d089 in zephir_call_user_func_array_noex () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#15 0x00007fa0c093dc33 in zephir_call_user_func_array () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#16 0x00007fa0c09928eb in zim_Phalcon_Dispatcher_callActionMethod () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#17 0x0000000000b2b7e7 in zend_call_function (fci=0x7ffd06c014b0, fci_cache=0x7ffd06c01490) at /tmp/php-7.3.18/Zend/zend_execute_API.c:770
#18 0x00007fa0c094c908 in zephir_call_user_function () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#19 0x00007fa0c094ce06 in zephir_call_class_method_aparams () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#20 0x00007fa0c098fe49 in zim_Phalcon_Dispatcher_dispatch () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#21 0x0000000000b2b7e7 in zend_call_function (fci=0x7ffd06c02820, fci_cache=0x7ffd06c02800) at /tmp/php-7.3.18/Zend/zend_execute_API.c:770
#22 0x00007fa0c094c908 in zephir_call_user_function () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#23 0x00007fa0c094ce06 in zephir_call_class_method_aparams () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#24 0x00007fa0c0a55db4 in zim_Phalcon_Mvc_Application_handle () from /usr/local/php7.3/lib/php/extensions/debug-non-zts-20180731/phalcon.so
#25 0x0000000000b2b7e7 in zend_call_function (fci=0x7ffd06c037f0, fci_cache=0x7ffd06c037d0) at /tmp/php-7.3.18/Zend/zend_execute_API.c:770
#26 0x00007fa0bfd48371 in zephir_call_user_function (object_pp=0x7ffd06c03d40, obj_ce=0x24ec0b0, type=zephir_fcall_method, function_name=0x7ffd06c03950, 
    retval_ptr=0x7fa0c7820140, cache_entry=0x0, cache_slot=0, param_count=1, params=0x7ffd06c03b20) at /tmp/kplus/kernel/fcall.c:378
#27 0x00007fa0bfd48998 in zephir_call_class_method_aparams (return_value=0x7fa0c7820140, ce=0x24ec0b0, type=zephir_fcall_method, object=0x7ffd06c03d40, 
    method_name=0x7fa0bfd8f9a8 "handle", method_len=6, cache_entry=0x0, cache_slot=0, param_count=1, params=0x7ffd06c03b20)
    at /tmp/kplus/kernel/fcall.c:516
#28 0x00007fa0bfd570fd in zephir_return_call_class_method (return_value=0x7fa0c7820140, ce=0x24ec0b0, type=zephir_fcall_method, object=0x7ffd06c03d40, 
    method_name=0x7fa0bfd8f9a8 "handle", method_len=6, cache_entry=0x0, cache_slot=0, param_count=1, params=0x7ffd06c03b20) at ./kernel/fcall.h:384
#29 0x00007fa0bfd60c96 in zim_Kplus_Application_handle (execute_data=0x7fa0c7820160, return_value=0x7fa0c7820140)
    at /tmp/kplus/kplus/application.zep.c:1038
#30 0x0000000000ba7431 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /tmp/php-7.3.18/Zend/zend_vm_execute.h:1106
#31 0x0000000000c0e37e in execute_ex (ex=0x7fa0c7820030) at /tmp/php-7.3.18/Zend/zend_vm_execute.h:55531
#32 0x0000000000c13994 in zend_execute (op_array=0x7fa0c7802100, return_value=0x0) at /tmp/php-7.3.18/Zend/zend_vm_execute.h:60939
#33 0x0000000000b426ec in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tmp/php-7.3.18/Zend/zend.c:1568
#34 0x0000000000ab1f8c in php_execute_script (primary_file=0x7ffd06c06790) at /tmp/php-7.3.18/main/main.c:2639
#35 0x0000000000c258e9 in main (argc=6, argv=0x7ffd06c069c8) at /tmp/php-7.3.18/sapi/fpm/fpm/fpm_main.c:1951
```

**Comment by zuozhehao** [comment]
dev 分支正常了

**Comment by laruence** [comment]
啊？ 你说清楚，是说pecl 的yar 502， 但是github master分支正常？ 你用的啥版本 。
